CREATE TABLE USER (
  ID        INT PRIMARY KEY AUTO_INCREMENT,
  USERNAME  VARCHAR(50) NOT NULL,
  PASSWORD  VARCHAR(50) NOT NULL,
  EMAIL     VARCHAR(50) NOT NULL,
  ROLE      INT         NOT NULL,
  FIRSTNAME VARCHAR(50),
  LASTNAME  VARCHAR(50),
  DOB       DATE,
  BALANCE   DECIMAL(19, 2),
  UUID      UUID
);

CREATE TABLE COLOR (
  ID       INT PRIMARY KEY AUTO_INCREMENT,
  VALUE_EN VARCHAR(255) NOT NULL,
  VALUE_RU VARCHAR(255) NOT NULL
);

CREATE TABLE MANUFACTURER (
  ID    INT PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(255) NOT NULL
);

CREATE TABLE MODEL (
  ID    INT PRIMARY KEY AUTO_INCREMENT,
  VALUE VARCHAR(255) NOT NULL
);

CREATE TABLE VEHICLE (
  VEHICLE_TYPE           INT            NOT NULL,
  ID                     INT PRIMARY KEY AUTO_INCREMENT,
  FUEL_TYPE              INT            NOT NULL,
  MILEAGE                DECIMAL(19, 2) NOT NULL CHECK (MILEAGE >= 0),
  OPERABLE               BOOLEAN        NOT NULL,
  PRODUCTION_YEAR        INTEGER        NOT NULL CHECK (PRODUCTION_YEAR >= 1950),
  RENT_PRICE             DECIMAL(8, 2)  NOT NULL CHECK (RENT_PRICE >= 1000),
  DOORS_NUMBER           INT CHECK ((DOORS_NUMBER >= 1) AND (DOORS_NUMBER <= 9)),
  PASSENGER_SEATS_NUMBER INT CHECK ((PASSENGER_SEATS_NUMBER <= 99) AND (PASSENGER_SEATS_NUMBER >= 1)),
  STANDING_PLACES_NUMBER INT CHECK ((STANDING_PLACES_NUMBER <= 199) AND (STANDING_PLACES_NUMBER >= 7)),
  CONDITIONER            BOOLEAN,
  ENCLOSED               BOOLEAN,
  MAX_PAYLOAD            DECIMAL(19, 2) CHECK ((MAX_PAYLOAD >= 1) AND (MAX_PAYLOAD <= 105)),
  TIPPER                 BOOLEAN,
  DRIVER_ID              INT,
  COLOR_ID               INT            NOT NULL,
  MANUFACTURER_ID        INT            NOT NULL,
  MODEL_ID               INT            NOT NULL
);

CREATE TABLE VH_ORDER (
  ID           INT PRIMARY KEY AUTO_INCREMENT,
  DATE_ORDERED TIMESTAMP      NOT NULL,
  DATE_START   DATE           NOT NULL,
  DAYS_COUNT   INTEGER        NOT NULL CHECK (DAYS_COUNT >= 1),
  STATUS       INT,
  SUM          DECIMAL(11, 2) NOT NULL CHECK (SUM >= 1000),
  CLIENT_ID    INT            NOT NULL,
  VEHICLE_ID   INT            NOT NULL
);

ALTER TABLE VEHICLE ADD CONSTRAINT FK_9SV39TI2YXUM3V6EUGMIKBYEY FOREIGN KEY (DRIVER_ID) REFERENCES USER (ID) NOCHECK;
ALTER TABLE VEHICLE ADD CONSTRAINT FK_CCU1GWCBLXB1Y4IIRID79C4F9 FOREIGN KEY (MODEL_ID) REFERENCES MODEL (ID) NOCHECK;
ALTER TABLE VEHICLE ADD CONSTRAINT FK_Q5K5YY3U3YJX79YJOG5F7DPN7 FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER (ID) NOCHECK;
ALTER TABLE VEHICLE ADD CONSTRAINT FK_7URFG3EARNO9AXMNF5C7E7XCW FOREIGN KEY (COLOR_ID) REFERENCES COLOR (ID) NOCHECK;
ALTER TABLE VH_ORDER ADD CONSTRAINT FK_HTVKB0U18F5DJWNUYS7EJ3S24 FOREIGN KEY(CLIENT_ID) REFERENCES USER(ID) NOCHECK;
ALTER TABLE VH_ORDER ADD CONSTRAINT FK_LPOHI5D3YXRTVR9RDAPUU31QS FOREIGN KEY(VEHICLE_ID) REFERENCES VEHICLE(ID) NOCHECK;